# jcpd/docker-dotclear:latest
volumes:
  dc_app:
  dc_db:

services:
  dc_db:
    image: mariadb:latest
    container_name: dotcleardb
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - dc_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dotclear_root
      MYSQL_DATABASE: dotclear_db
      MYSQL_USER: dotclear_user
      MYSQL_PASSWORD: dotclear_pwd
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  dc_app:
    image: jcpd/docker-dotclear:latest
    container_name: dotclearphp
    restart: unless-stopped
    volumes:
      - dc_app:/var/www/dotclear
    ports:
      - 80:80
    depends_on:
      dc_db: # MYSQL database service
        condition: service_healthy # Waiting for database ready
    environment:
      DC_DBDRIVER: mysqlimb4
      DC_DBHOST: dc_db
      DC_DBNAME: dotclear_db
      DC_DBUSER: dotclear_user
      DC_DBPASSWORD: dotclear_pwd
      DC_DBPREFIX: dc_
      DC_ADMINMAILFROM: contact@exemple.com