services:

  # MYSQL database service
  dc_db:
    image: mariadb:latest
    container_name: dotcleardb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - dc_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dotclear_root
      MYSQL_DATABASE: dotclear_db
      MYSQL_USER: dotclear_user
      MYSQL_PASSWORD: dotclear_pwd

  # PHP-FPM Service
  dc_app:
    image: jcpd/docker-dotclear:latest
    container_name: dotclearphp
    volumes:
      - dc_app:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - dc_db # MYSQL database service

volumes:
  dc_app: # NGINX volume
  dc_db: # MYSQL volume