name: Build and push dev image

on:
  schedule:
  - cron: '0 1 * * *'
  workflow_dispatch:

env:
  DOTCLEAR_IMAGE: jcpd/docker-dotclear
  DOTCLEAR_CANAL: unstable

jobs:
  do_image:
    name: Build dev image and push to Docker hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          sbom: true
          push: true
          tags: ${{ env.DOTCLEAR_IMAGE }}:dev
          build-args: CANAL=${{ env.DOTCLEAR_CANAL }}
          platforms: linux/386,linux/amd64,linux/arm/V6

      - name: Send Telegram Message Ok
        uses: appleboy/telegram-action@master
        env:
          GITHUB_CONTEXT: ${{toJSON(github)}}
        with:
          to: ${{ secrets.TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: Image __${{ env.DOTCLEAR_IMAGE }}:dev__ successfully generated.