name: Update Docker Hub Description
on:
  push:
    branches:
      - master
    paths:
      - README.md
  workflow_dispatch:

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: jcpd/docker-dotclear
        short-description: ${{ github.event.repository.description }}
        readme-filepath: ./README.md
        enable-url-completion: true